import Head from 'next/head';
import { useEffect } from 'react';

export default function Home() {
	// how to apply styles/classes to <body>
	useEffect(() => {
		// document.body.classList.add('min-h-screen');
		// document.body.classList.add('grid');
		// document.body.classList.add('place-content-center');
		// document.body.classList.add('radial-blue');
	});
	return (
		<div>
			<Head>
				<title>Tailwind with Next JS!</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<h1>Tailwind ready to go!</h1>
			</main>
		</div>
	);
}
