import Head from 'next/head';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Tailwind with Next JS!</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<h1>Tailwind ready to go!</h1>
			</main>
		</div>
	);
}
